### PR TITLE
Make worker connections configurable

### PR DESCRIPTION
**Pull request by sbesson**
See discussion in https://github.com/openmicroscopy/prod-playbooks/pull/37#issuecomment-362008707

This PR makes [worker_connections](http://nginx.org/en/docs/ngx_core_module.html#worker_connections) configurable via the role.

Proposed tag: `1.7.0`

### CODE REVIEW

**Comment by joshmoore** [comment]
LGTM, but I have a similar question as on https://github.com/openmicroscopy/ansible-role-network/pull/2 a la https://github.com/maruina/ansible-role-nginx/blob/master/templates/nginx.conf.j2

**Comment by manics** [comment]
I think this change is fine since the number of directives we're likely to need in nginx.conf is limited, unlike the main proxy config which could do with a refactor.

**Comment by manics** [comment]
Expanding on https://github.com/openmicroscopy/ansible-role-network/pull/2#issuecomment-363383282 a bit more: by having enabling arbitrary configs in the form of key-value pairs we're telling the user "for these configs go to the upstream documentation to understand what's going on, and it's your problem if there's a mistake", whereas by having explicit parameters which are documented in the README we're saying (or at lerast trying to say) "these are things you may want to change, and we'll ensure it goes in the correct place in your config file even if we don't validate the values you've specified".

Obviously it's not clear cut choice.

**Comment by sbesson** [comment]
f25c114  is my initial attempt at refactoring the top-level nginx configuration template using a dictionary of key/values as discussed above. I haven't done the `log_format` section yet. Looking forward to hearing feedback at the upcoming sysadmin meeting.

**Comment by manics** [comment]
What are your expectations for how peopel would use these new variables?
- Override `nginx_proxy_main_conf.worker_processes`? (straightforward)
- Override `nginx_proxy_main_conf`? (means they have to redefine the entire dictionary, unless they've modified their ansible.cfg to merge dicts)

**Comment by sbesson** [comment]
Force pushed away f25c114 as discussed this morning

**Comment by joshmoore** [comment]
Tag pushed

**Pull request merged**
