### PR TITLE
Add parameter for 404

### PR DESCRIPTION
**Pull request by sbesson**
Discussed with @kennethgillen and @manics during testing, this PR extends the nginx-proxy role to allow the comment `error_page 404` line to be configured by variable using a the `nginx_proxy_404` variable.

Proposed tag: `1.4.0`

### CODE REVIEW

**Comment by kennethgillen** [comment]
👍  nice!

**Comment by kennethgillen** [comment]
@sbesson - if this is the version which allowed the 404 to work on infra-testpr over the past couple of days, then I'd say big 👍  for merging. Current www-dev does _not_ have the 404 working, which is probably a lack of this being merged.

**Comment by sbesson** [comment]
@kennethgillen this has not been included in any deployment so far. The 404 page works under certain conditions (namely if no match is found when trying to apply redirect_map) but there is no default error code set up. If that is fine with you, I propose to open a PR against infrastructure to configure the default 404 page.

**Comment by manics** [comment]
LGTM based on https://github.com/openmicroscopy/infrastructure/pull/292/commits/25ae422a3198402cd9701631f84ca14a41eee9f6 infra-testpr.

> but there is no default error code set up

Sorry, I don't understand what you mean by this.

**Comment by sbesson** [comment]
Sorry I meant that with the current state of the role, you cannot configure the custom URI for 404 error codes but you can do so in the `nginx_proxy_redirect_*` section using the `default` match (which is what this PR tries to enable).

**Pull request merged**
