### PR TITLE
Allow limiting access to proxied backends by method

### PR DESCRIPTION
**Pull request by manics**
This adds a new optional field `limit_methods` for proxied sites. This can provide additional security to backends such as devspace Jenkins by only allowing `GET` requests. See http://nginx.org/en/docs/http/ngx_http_core_module.html#limit_except

For example:
```
      nginx_proxy_backends:
      - name: devspace-backend
        location: /
        server: https://DEVSPACE_IP:8443
        limit_methods: GET
```
This prevents logins to Jenkins

### CODE REVIEW

**Comment by joshmoore** [comment]
Nice. `1.6.0` as an addition?

**Comment by manics** [comment]
Sounds good

**Comment by joshmoore** [comment]
Cool. Are the tests in a state that a non-GET/HEAD could be tried and found impossible?

**Comment by manics** [comment]
How's this? It relies on:
```
# curl -I -X POST http://www.openmicroscopy.org/
HTTP/1.1 405 Not Allowed
Server: nginx/1.12.1
Date: Fri, 15 Dec 2017 17:56:04 GMT
Content-Type: text/html
Content-Length: 173
Connection: keep-alive
```
returning 405 vs 403:
```
# curl -I -X POST -H 'Host: other' http://localhost/limitget/
HTTP/1.1 403 Forbidden
Server: nginx/1.12.2
Date: Fri, 15 Dec 2017 17:56:41 GMT
Content-Type: text/html
Content-Length: 169
Connection: keep-alive
```
since you can't distinguish between the return code of the proxy and the return code of the backend.

In principle it's possible to do this with a self-contained server instead of an external site, but that's a lot more work and testing since it ends up talking to itself.

**Comment by joshmoore** [comment]
Ping @sbesson and @kennethgillen about hitting www.o.org from a test.

**Comment by kennethgillen** [comment]
Presumably the rate of test executions would be on the scale of ≈hundreds/day then no objections. Only worry would be pollution of stats.

**Pull request merged**
